name: Hello Python action

on:
  push:
  workflow_dispatch: 

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Hello World
        run: |
          python -c "print('Hello, world!')"
