on:
  push:
jobs:
  Job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: sleep 3
  Job2:
    needs: Job44
    name: Job 2
    runs-on: ubuntu-latest
    steps:
    - name: sleep
      run: sleep 5
  Job3:
    needs: Job1
    name: Job 3
    runs-on: ubuntu-ubuntu-latest
    steps:
      - name: sleep
        run: sleep 3 
